// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb, defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB-cKo0YJ5K9XO4yHFZoSQVw2EBb5bBIA',
    appId: '1:272988590091:web:6c59826ba304314947f70e',
    messagingSenderId: '272988590091',
    projectId: 'yassin0',
    authDomain: 'yassin0.firebaseapp.com',
    storageBucket: 'yassin0.firebasestorage.app',
    measurementId: 'G-Q6F9XRG6KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB-cKo0YJ5K9XO4yHFZoSQVw2EBb5bBIA',
    appId: '1:272988590091:android:6c59826ba304314947f70e',
    messagingSenderId: '272988590091',
    projectId: 'yassin0',
    storageBucket: 'yassin0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB-cKo0YJ5K9XO4yHFZoSQVw2EBb5bBIA',
    appId: '1:272988590091:ios:6c59826ba304314947f70e',
    messagingSenderId: '272988590091',
    projectId: 'yassin0',
    storageBucket: 'yassin0.firebasestorage.app',
    iosBundleId: 'com.example.zamel_2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB-cKo0YJ5K9XO4yHFZoSQVw2EBb5bBIA',
    appId: '1:272988590091:macos:6c59826ba304314947f70e',
    messagingSenderId: '272988590091',
    projectId: 'yassin0',
    storageBucket: 'yassin0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB-cKo0YJ5K9XO4yHFZoSQVw2EBb5bBIA',
    appId: '1:272988590091:windows:6c59826ba304314947f70e',
    messagingSenderId: '272988590091',
    projectId: 'yassin0',
    storageBucket: 'yassin0.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCB-cKo0YJ5K9XO4yHFZoSQVw2EBb5bBIA',
    appId: '1:272988590091:linux:6c59826ba304314947f70e',
    messagingSenderId: '272988590091',
    projectId: 'yassin0',
    storageBucket: 'yassin0.firebasestorage.app',
  );
}